apiVersion: v1
kind: Secret
metadata:
  name: {{ include "better-chatbot.fullname" . }}-secret
  labels:
    {{- include "better-chatbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

